sources:
  bundler: true
  yarn: true

# Dependencies with these licenses are allowed by default.
allowed:
  - apache-2.0
  - 0bsd
  - bsd-2-clause
  - bsd-3-clause
  - cc-by-4.0
  - cc-by-3.0
  - cc0-1.0
  - isc
  - mit
  - unlicense
  - wtfpl